config/routes.rb
Myapp::Application.routes.draw do
  devise_for :users

  resources :projects, except: [:edit, :show, :new] do
    resources :tasks, except: [:new, :show] do
      post :sort, on: :collection
    end
  end

  root :to => 'projects#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can :manage, Project do |project|
      project.user == user
    end

    can :manage, Task do |task|
      task.project.user == user
    end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user

  has_many :tasks, dependent: :destroy, order: :priority

  attr_accessible :user, :name

  validates :user, presence: true
  validates :name, presence: true, length: { maximum: 255 }
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  #acts_as_list scope: :project

  attr_accessible :project_id, :name, :deadline, :finish, :priority

  validates :project, presence: true
  validates :name, presence: true, length: { maximum: 255 }
  validates :deadline, presence: true, timeliness: { type: :date }
  validates :finish, inclusion: { in: [true, false] }
  validates :priority, presence: true, numericality: { only_integer: true, greater_than: 0  }

  scope :sort_by_priority, order('priority ASC')
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :projects, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate_user!

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  protected
  def layout_by_resource
    if devise_controller?
      "layout_name_for_devise"
    else
      "application"
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end
end

app/controllers/projects_controller.rb
class ProjectsController < InheritedResources::Base
  load_and_authorize_resource
  actions :all, except: [:edit, :show, :new]
  #respond_to :html, only: [:index]
  #respond_to :js, except: :update
  respond_to :json#, only: :update

  protected
  def begin_of_association_chain
    current_user
  end

  def build_resource
    super.tap do |attr|
      attr.user = current_user
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < InheritedResources::Base
  load_and_authorize_resource
  respond_to :js, except: :edit
  respond_to :html, only: :edit
  belongs_to :project
  actions :all, except: [:new, :show]
  custom_actions collection: :sort
  layout false, only: [:edit]

  def sort
    params[:task].each_with_index do |id, index|
      collection.update_all( { priority: index + 1 }, { id: id } )
    end
    render nothing: true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    case flash_type
    when :success
      "alert-success"
    when :error
      "alert-error"
    when :alert
      "alert-block"
    when :notice
      "alert-info"
    else
      flash_type.to_s
    end
  end
end

app/views/layouts/_flash_messages.html.haml
#flashes
  - flash.each do |type, message|
    %div{ class: "alert flash #{ bootstrap_class_for(type) } fade in" }
      %button.close{ :'data-dismiss' => 'alert'} ×
      = message

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Todo List (Ruby Garage)
    = stylesheet_link_tag    "application", media: "all"
    /[if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1.0' }
    = csrf_meta_tags
  %body
    .container
      .row
        .span1
        .span10
          .current_user
            %strong= current_user.email
            = link_to "Sign out", destroy_user_session_path, method: :delete
          %br
          = render 'layouts/flash_messages'
        .span1
        %br
      .row
        .span3
        .span6
          .header-title
            SIMPLE TODO LISTS
            .title2 FROM RUBY GARAGE
        .span3
      = yield
    %footer
      .footer-content
        %p &copy; Ruby Garage
  = javascript_include_tag "application"
  = yield :js

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %title Todo List (Ruby Garage)
    = stylesheet_link_tag    "devise", media: "all"
    /[if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    = csrf_meta_tags
  %body
    .container
      = render 'layouts/flash_messages'
      = yield
    = javascript_include_tag "application"

app/views/overlays/tasks/_edit_task.html.haml
#edit-task.modal.fade
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h3 Edit Task
  .modal-body

app/views/projects/_project.html.haml
%div{ class: 'project', id: dom_id(project) }
  .row
    .span1
    .span10
      .project-header
        .row
          .span1
            .icon_table_blue
          .span8
            .project-name= best_in_place project, :name, activator: "#edit_#{dom_id(project)}"
          .span1
            .links
              = link_to image_tag('edit_blue.png'), 'javascript:;', id: "edit_#{dom_id(project)}"
              %span.delimiter
                \|
              = link_to image_tag('trash.png'), project, method: :delete, remote: true, confirm: 'Are you sure?', id: "delete_#{dom_id(project)}"
    .span1
  .row
    .span1
    .span10
      %div{ id: "#{dom_id(project)}_new_task", class: 'new-task' }
        = render 'tasks/form', { project: project, task: Task.new }
    .span1
  .row
    .span1
    .span10
      %table.table.tasks-list{ id: "#{dom_id(project)}_tasks_list", :'data-update-url' => sort_project_tasks_path(project) }
        = render project.tasks
    .span1

app/views/projects/create.js.haml
- if resource.new_record?
  $('#new_project_modal .modal-body').html("#{ j(render 'form', project: resource) }")
- else
  $('#projects_list').append("#{ j(render 'projects/project', project: resource) }")
  $('#new_project_modal').modal('hide')
  Message.show("#{flash[:notice]}")
  $(".best_in_place").best_in_place()
  Task.init_datepicker()
$('form').validate()

app/views/projects/destroy.js.haml
$("##{dom_id(resource)}").remove()
Message.show("#{flash[:notice]}")

app/views/projects/index.html.haml
#projects_list{ 'data-projects' => collection.to_json }

-#= render 'overlays/tasks/edit_task'

app/views/tasks/_form.html.haml
.row
  = simple_form_for [project, task], validate: true, html: { class: 'form-inline' }, remote: true do |f|
    .span1
      .icon_plus_green
    .span5
      = f.input :name, placeholder: 'Start typing here to create a task...', label: false
    .span2
      = f.input :deadline, as: :string, label: false, placeholder: 'Date',
                           input_html: { class: 'datepicker', id: "datepicker_#{dom_id(project)}" }
    .span2
      = f.button :submit, value: 'Add Task', class: 'btn btn-success'

app/views/tasks/_task.html.haml
%tr{id: dom_id(task)}
  %td.first= check_box_tag :finish, !task.finish?, task.finish?, class: 'task_finish', :'data-path' => project_task_path(task.project, task)
  %td.second= task.name
  %td= task.deadline
  %td.last
    %span.handle= image_tag('move.png')
    %span.delimiter-grey
      \|
    = link_to image_tag('edit_grey.png'), edit_project_task_path(task.project, task), :'data-toggle' => :modal,
                                          :'data-target' => '#edit-task', class: 'edit-task', id: "edit_#{dom_id(task)}"
    %span.delimiter-grey
      \|
    = link_to image_tag('trash_grey.png'), project_task_path(task.project, task), confirm: "Are you sure?",
                                           remote: true, method: :delete, id: "delete_#{dom_id(task)}"

app/views/tasks/create.js.haml
- unless resource.new_record?
  Message.show("#{flash[:notice]}")
  $("##{ dom_id(parent) }_tasks_list").html("#{ j(render parent.tasks) }")
  $("##{ dom_id(parent) }_new_task").find("input[type='text']").val('')
  Task.sortable()
  $("##{ dom_id(parent) }_new_task").html("#{ j(render 'tasks/form', { project: parent, task: Task.new }) }")
- else
  $("##{ dom_id(parent) }_new_task").html("#{ j(render 'tasks/form', { project: parent, task: resource }) }")
Task.init_datepicker()
$('form').validate()

app/views/tasks/destroy.js.haml
$("##{ dom_id(resource) }").remove()
Message.show("#{flash[:notice]}")

app/views/tasks/edit.html.haml
= simple_form_for [parent, resource], validate: true, remote: true, html: { class: 'form-horizontal' } do |f|
  = f.input :name, placeholder: 'Start typing here to create a task...'
  = f.input :deadline, as: :string, placeholder: 'Date',
                       input_html: { class: 'datepicker', id: "datepicker_#{dom_id(resource)}" }
  .modal-footer
    %button.btn{ :'aria-hidden' => true, :'data-dismiss' => :modal } Close
    = f.button :submit, class: 'btn btn-primary', value: 'Update'

:javascript
  Task.init_datepicker()

app/views/tasks/update.js.haml
- if resource.errors.blank?
  Message.show("#{flash[:notice]}")
  $("##{ dom_id(parent) }_tasks_list").html("#{ j(render parent.tasks) }")
  $('#edit-task').modal('hide')
- else
  $("#edit-task .modal-body").html("#{ j(render template: 'tasks/edit') }")